### ISSUE TITLE
please provide d3 files

### ISSUE THREAD

**Issue by rrutia** [lockfale/ARF#11]
When I use the d3 files from the d3js.org website it does not work with your files.

How do we make your files work with d3?

Thanks

**Comment by s0lray** [comment]
All of the the website's files are in the repo.  I'm using the standard d3.min.js files.  I'm not sure how else I can help, but let me know if there is something I can do.

**Comment by treefort** [comment]
@rrutia it works with d3 v3.5.16. (see [this jsfiddle](https://jsfiddle.net/dbh5u2gq/2/))

@s0lray I'll follow up with a PR to include this info

**Comment by rrutia** [comment]
@treefort version d3 v3.5.16 fixed the problem ! Thank You very much

@s0lray Thanks for replying back

**Comment by s0lray** [comment]
Derp, I didn't realize how quickly d3 was pushing out updates.  Good catch @treefort.  @rrutia, @treefort also submitted a PR to make this even easier with package management.  I'll merge that in just a minute.
