### ISSUE TITLE
MrLooquer. IPv6 Scan

### ISSUE THREAD

**Issue by ffr4nz** [lockfale/ARF#14]
As Shodan, MrLooquer discover new devices on Internet. The difference is that MrLooquer is focus on IPv6 protocol and as Shodan we are pioneering on IPv6 scanning.

MrLooquer: IPv6 Intelligence.
https://mrlooquer.com

**Comment by s0lray** [comment]
Added Sept 1st, 2016.  Thanks for the suggestion!
