### ISSUE TITLE
arf.json editor

### ISSUE THREAD

**Issue by rrutia** [lockfale/ARF#15]
Hi again

What is a good editor for json files?

I find it really hard to edit this file with notepad++

Thanks !!

**Comment by treefort** [comment]
Hey @rrutia, 

I typically use [Atom](http://atom.io) and just open the JSON file in Chrome (with [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc) installed) to test for valid syntax. 

There's also a cleverly-named Atom package called [atom-json-editor](https://atom.io/packages/atom-json-editor) that may simplify the editing workflow, but I've never tried it out personally.

The [atom-beautify](https://atom.io/packages/atom-beautify) package is great for things like automatic formatting/indentation/etc., and it works for many different languages.

Hope that helps!

**Comment by rrutia** [comment]
@treefort Thanks
