### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by x1sn0tz** [lockfale/ARF#16]
1) Search Engines -> Code Search -> Meanpath
meanpath.com’s server DNS address could not be found
Not sure whether it's my DNS problem or a global one

2) Search Engines -> Search Tools
Google Alerts are listed twice 

3) Email Address -> Email Search -> Find Any Email Checker
default backend - 404 error

**Comment by s0lray** [comment]
Thanks!  I removed the duplicate google alerts and dropped the other two down to an alternate / dead tools section to be monitored for a while.  I will push out the update tonight.
