### ISSUE TITLE
Images -> Instagram services needs update

### ISSUE THREAD

**Issue by x1sn0tz** [lockfale/ARF#20]
**http://collec.to/**
Instagram from 2th June 2016 has blocked the application that allows us to give you the best experience. We apologize for the inconvenience. We ask you to leave your email to receive news about the projec

**http://www.picturegr.am/**
There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

**https://instagr.in/explore/**
Not reachable

**Comment by s0lray** [comment]
Ugh.  An update to Instagram's API killed almost every good tool that was in the list.  Removed these three and a few others in tonight's release.
