### ISSUE TITLE
"That One Privacy Guy's VPN Comparison Chart" moved to new location

### ISSUE THREAD

**Issue by x1sn0tz** [lockfale/ARF#21]
OpSec -> Anonymous Browsing -> Anonymous VPNs -> That One Privacy Guy's VPN Comparison Chart URL should be changed to https://thatoneprivacysite.net/

**Comment by s0lray** [comment]
Nice, this looks much better than the google doc.  I'm glad he updated it.  Thanks for the notice, added in tonight's release.
