### ISSUE TITLE
Broken link or service is no longer available

### ISSUE THREAD

**Issue by alexeypetrenko** [lockfale/ARF#7]
[Link](http://www.tcpiputils.com/keyword-analysis) to a *Keyword Analysis* under *Domain Names* -> *Analytics* leads to a *Page not found* page.

**Comment by s0lray** [comment]
Thanks!  I should be pushing an update this weekend so I'll roll this into it.

**Comment by s0lray** [comment]
Removed that link and found a similar tool as a replacement.
